### ISSUE TITLE
dist file can't update when use rolllup dev mode

### ISSUE THREAD

**Issue by kaxifakl** [unplugin/unplugin-vue#127] opened 2023-09-02 01:41 UTC
### Describe the bug

use rollup dev mode, 
change template or script in .vue file,
watch mode show that have something changed,but the dist file is still old content.

### Reproduction

rollup v3.28.1 bundles ./src/panels/default/index.ts → dist/panels/default... created dist/panels/default in 228ms  [2023-09-02 09:38:31] waiting for changes...

### System Info

```Shell
nodejs build vue3 sfc
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment] 2023-09-02 07:25
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed** 2023-09-25 07:03 UTC
